# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 工作流名称
name: Java CI with Maven

# 监听
on:
  # 当向master分支push操作的时候执行操作
  push:
    # 分支列表
    branches: [ master ]

jobs:
  # 持续集成
  build:
    # 指定操作系统（自动生成），在ubuntu上执行下列操作
    runs-on: ubuntu-latest
    steps:
      # 将步骤暴露出去为actions，类似于发布出去，让别人调用，这是GitHub提供的actions，只要一执行use就会执行一系列操作，此步是将仓库中的源码提取出来，并不需要关心位置
      - uses: actions/checkout@v2
      # 声明步骤名称
      - name: Set up JDK 11
        # 把ubuntu中的jdk版本设为11
        uses: actions/setup-java@v1
        # 参数赋给上边的use
        with:
          java-version: 11
      - name: Build with Maven
        # 声明maven打包的命令，完成测试 构建 打包
        run: mvn -B package --file pom.xml
